// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: google/protobuf/service_options.proto

package serviceoptionspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LambdaIntegration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FunctionName  string                 `protobuf:"bytes,1,opt,name=function_name,json=functionName,proto3" json:"function_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LambdaIntegration) Reset() {
	*x = LambdaIntegration{}
	mi := &file_google_protobuf_service_options_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LambdaIntegration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LambdaIntegration) ProtoMessage() {}

func (x *LambdaIntegration) ProtoReflect() protoreflect.Message {
	mi := &file_google_protobuf_service_options_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LambdaIntegration.ProtoReflect.Descriptor instead.
func (*LambdaIntegration) Descriptor() ([]byte, []int) {
	return file_google_protobuf_service_options_proto_rawDescGZIP(), []int{0}
}

func (x *LambdaIntegration) GetFunctionName() string {
	if x != nil {
		return x.FunctionName
	}
	return ""
}

type RestIntegration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestIntegration) Reset() {
	*x = RestIntegration{}
	mi := &file_google_protobuf_service_options_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestIntegration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestIntegration) ProtoMessage() {}

func (x *RestIntegration) ProtoReflect() protoreflect.Message {
	mi := &file_google_protobuf_service_options_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestIntegration.ProtoReflect.Descriptor instead.
func (*RestIntegration) Descriptor() ([]byte, []int) {
	return file_google_protobuf_service_options_proto_rawDescGZIP(), []int{1}
}

func (x *RestIntegration) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type SqsIntegration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueueUrl      string                 `protobuf:"bytes,1,opt,name=queue_url,json=queueUrl,proto3" json:"queue_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SqsIntegration) Reset() {
	*x = SqsIntegration{}
	mi := &file_google_protobuf_service_options_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SqsIntegration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SqsIntegration) ProtoMessage() {}

func (x *SqsIntegration) ProtoReflect() protoreflect.Message {
	mi := &file_google_protobuf_service_options_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SqsIntegration.ProtoReflect.Descriptor instead.
func (*SqsIntegration) Descriptor() ([]byte, []int) {
	return file_google_protobuf_service_options_proto_rawDescGZIP(), []int{2}
}

func (x *SqsIntegration) GetQueueUrl() string {
	if x != nil {
		return x.QueueUrl
	}
	return ""
}

var file_google_protobuf_service_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*LambdaIntegration)(nil),
		Field:         40001,
		Name:          "google.api.lambda_integration",
		Tag:           "bytes,40001,opt,name=lambda_integration",
		Filename:      "google/protobuf/service_options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*RestIntegration)(nil),
		Field:         40002,
		Name:          "google.api.rest_integration",
		Tag:           "bytes,40002,opt,name=rest_integration",
		Filename:      "google/protobuf/service_options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*SqsIntegration)(nil),
		Field:         40003,
		Name:          "google.api.sqs_integration",
		Tag:           "bytes,40003,opt,name=sqs_integration",
		Filename:      "google/protobuf/service_options.proto",
	},
}

// Extension fields to descriptorpb.ServiceOptions.
var (
	// optional google.api.LambdaIntegration lambda_integration = 40001;
	E_LambdaIntegration = &file_google_protobuf_service_options_proto_extTypes[0]
	// optional google.api.RestIntegration rest_integration = 40002;
	E_RestIntegration = &file_google_protobuf_service_options_proto_extTypes[1]
	// optional google.api.SqsIntegration sqs_integration = 40003;
	E_SqsIntegration = &file_google_protobuf_service_options_proto_extTypes[2]
)

var File_google_protobuf_service_options_proto protoreflect.FileDescriptor

const file_google_protobuf_service_options_proto_rawDesc = "" +
	"\n" +
	"%google/protobuf/service_options.proto\x12\n" +
	"google.api\x1a google/protobuf/descriptor.proto\"8\n" +
	"\x11LambdaIntegration\x12#\n" +
	"\rfunction_name\x18\x01 \x01(\tR\ffunctionName\"%\n" +
	"\x0fRestIntegration\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"-\n" +
	"\x0eSqsIntegration\x12\x1b\n" +
	"\tqueue_url\x18\x01 \x01(\tR\bqueueUrl:r\n" +
	"\x12lambda_integration\x12\x1f.google.protobuf.ServiceOptions\x18\xc1\xb8\x02 \x01(\v2\x1d.google.api.LambdaIntegrationR\x11lambdaIntegration\x88\x01\x01:l\n" +
	"\x10rest_integration\x12\x1f.google.protobuf.ServiceOptions\x18¸\x02 \x01(\v2\x1b.google.api.RestIntegrationR\x0frestIntegration\x88\x01\x01:i\n" +
	"\x0fsqs_integration\x12\x1f.google.protobuf.ServiceOptions\x18ø\x02 \x01(\v2\x1a.google.api.SqsIntegrationR\x0esqsIntegration\x88\x01\x01Bd\n" +
	"\x0ecom.google.apiB\x10AnnotationsProtoP\x01Z7google.golang.org/protobuf/types/known/serviceoptionspb\xa2\x02\x04GAPIb\x06proto3"

var (
	file_google_protobuf_service_options_proto_rawDescOnce sync.Once
	file_google_protobuf_service_options_proto_rawDescData []byte
)

func file_google_protobuf_service_options_proto_rawDescGZIP() []byte {
	file_google_protobuf_service_options_proto_rawDescOnce.Do(func() {
		file_google_protobuf_service_options_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_google_protobuf_service_options_proto_rawDesc), len(file_google_protobuf_service_options_proto_rawDesc)))
	})
	return file_google_protobuf_service_options_proto_rawDescData
}

var file_google_protobuf_service_options_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_google_protobuf_service_options_proto_goTypes = []any{
	(*LambdaIntegration)(nil),           // 0: google.api.LambdaIntegration
	(*RestIntegration)(nil),             // 1: google.api.RestIntegration
	(*SqsIntegration)(nil),              // 2: google.api.SqsIntegration
	(*descriptorpb.ServiceOptions)(nil), // 3: google.protobuf.ServiceOptions
}
var file_google_protobuf_service_options_proto_depIdxs = []int32{
	3, // 0: google.api.lambda_integration:extendee -> google.protobuf.ServiceOptions
	3, // 1: google.api.rest_integration:extendee -> google.protobuf.ServiceOptions
	3, // 2: google.api.sqs_integration:extendee -> google.protobuf.ServiceOptions
	0, // 3: google.api.lambda_integration:type_name -> google.api.LambdaIntegration
	1, // 4: google.api.rest_integration:type_name -> google.api.RestIntegration
	2, // 5: google.api.sqs_integration:type_name -> google.api.SqsIntegration
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	3, // [3:6] is the sub-list for extension type_name
	0, // [0:3] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_google_protobuf_service_options_proto_init() }
func file_google_protobuf_service_options_proto_init() {
	if File_google_protobuf_service_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_google_protobuf_service_options_proto_rawDesc), len(file_google_protobuf_service_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 3,
			NumServices:   0,
		},
		GoTypes:           file_google_protobuf_service_options_proto_goTypes,
		DependencyIndexes: file_google_protobuf_service_options_proto_depIdxs,
		MessageInfos:      file_google_protobuf_service_options_proto_msgTypes,
		ExtensionInfos:    file_google_protobuf_service_options_proto_extTypes,
	}.Build()
	File_google_protobuf_service_options_proto = out.File
	file_google_protobuf_service_options_proto_goTypes = nil
	file_google_protobuf_service_options_proto_depIdxs = nil
}
