// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: google/protobuf/field_options.proto

package fieldoptionspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_google_protobuf_field_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50001,
		Name:          "tecmise.protocols.json_name",
		Tag:           "bytes,50001,opt,name=json_name",
		Filename:      "google/protobuf/field_options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50002,
		Name:          "tecmise.protocols.omitempty",
		Tag:           "varint,50002,opt,name=omitempty",
		Filename:      "google/protobuf/field_options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: ([]string)(nil),
		Field:         50003,
		Name:          "tecmise.protocols.validate",
		Tag:           "bytes,50003,rep,name=validate",
		Filename:      "google/protobuf/field_options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50004,
		Name:          "tecmise.protocols.description",
		Tag:           "bytes,50004,opt,name=description",
		Filename:      "google/protobuf/field_options.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional string json_name = 50001;
	E_JsonName = &file_google_protobuf_field_options_proto_extTypes[0]
	// optional bool omitempty = 50002;
	E_Omitempty = &file_google_protobuf_field_options_proto_extTypes[1]
	// repeated string validate = 50003;
	E_Validate = &file_google_protobuf_field_options_proto_extTypes[2]
	// optional string description = 50004;
	E_Description = &file_google_protobuf_field_options_proto_extTypes[3]
)

var File_google_protobuf_field_options_proto protoreflect.FileDescriptor

const file_google_protobuf_field_options_proto_rawDesc = "" +
	"\n" +
	"#google/protobuf/field_options.proto\x12\x11tecmise.protocols\x1a google/protobuf/descriptor.proto:?\n" +
	"\tjson_name\x12\x1d.google.protobuf.FieldOptions\x18ц\x03 \x01(\tR\bjsonName\x88\x01\x01:=\n" +
	"\tomitempty\x12\x1d.google.protobuf.FieldOptions\x18҆\x03 \x01(\bR\tomitempty:;\n" +
	"\bvalidate\x12\x1d.google.protobuf.FieldOptions\x18ӆ\x03 \x03(\tR\bvalidate:D\n" +
	"\vdescription\x12\x1d.google.protobuf.FieldOptions\x18Ԇ\x03 \x01(\tR\vdescription\x88\x01\x01B7Z5google.golang.org/protobuf/types/known/fieldoptionspbb\x06proto3"

var file_google_protobuf_field_options_proto_goTypes = []any{
	(*descriptorpb.FieldOptions)(nil), // 0: google.protobuf.FieldOptions
}
var file_google_protobuf_field_options_proto_depIdxs = []int32{
	0, // 0: tecmise.protocols.json_name:extendee -> google.protobuf.FieldOptions
	0, // 1: tecmise.protocols.omitempty:extendee -> google.protobuf.FieldOptions
	0, // 2: tecmise.protocols.validate:extendee -> google.protobuf.FieldOptions
	0, // 3: tecmise.protocols.description:extendee -> google.protobuf.FieldOptions
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	0, // [0:4] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_google_protobuf_field_options_proto_init() }
func file_google_protobuf_field_options_proto_init() {
	if File_google_protobuf_field_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_google_protobuf_field_options_proto_rawDesc), len(file_google_protobuf_field_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 4,
			NumServices:   0,
		},
		GoTypes:           file_google_protobuf_field_options_proto_goTypes,
		DependencyIndexes: file_google_protobuf_field_options_proto_depIdxs,
		ExtensionInfos:    file_google_protobuf_field_options_proto_extTypes,
	}.Build()
	File_google_protobuf_field_options_proto = out.File
	file_google_protobuf_field_options_proto_goTypes = nil
	file_google_protobuf_field_options_proto_depIdxs = nil
}
