// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: google/protobuf/method_options.proto

package methodoptionspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HttpIntegration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpIntegration) Reset() {
	*x = HttpIntegration{}
	mi := &file_google_protobuf_method_options_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpIntegration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpIntegration) ProtoMessage() {}

func (x *HttpIntegration) ProtoReflect() protoreflect.Message {
	mi := &file_google_protobuf_method_options_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpIntegration.ProtoReflect.Descriptor instead.
func (*HttpIntegration) Descriptor() ([]byte, []int) {
	return file_google_protobuf_method_options_proto_rawDescGZIP(), []int{0}
}

func (x *HttpIntegration) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

var file_google_protobuf_method_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*HttpIntegration)(nil),
		Field:         40001,
		Name:          "tecmise.protocols.http",
		Tag:           "bytes,40001,opt,name=http",
		Filename:      "google/protobuf/method_options.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional tecmise.protocols.HttpIntegration http = 40001;
	E_Http = &file_google_protobuf_method_options_proto_extTypes[0]
)

var File_google_protobuf_method_options_proto protoreflect.FileDescriptor

const file_google_protobuf_method_options_proto_rawDesc = "" +
	"\n" +
	"$google/protobuf/method_options.proto\x12\x11tecmise.protocols\x1a google/protobuf/descriptor.proto\")\n" +
	"\x0fHttpIntegration\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method:X\n" +
	"\x04http\x12\x1e.google.protobuf.MethodOptions\x18\xc1\xb8\x02 \x01(\v2\".tecmise.protocols.HttpIntegrationR\x04httpB8Z6google.golang.org/protobuf/types/known/methodoptionspbb\x06proto3"

var (
	file_google_protobuf_method_options_proto_rawDescOnce sync.Once
	file_google_protobuf_method_options_proto_rawDescData []byte
)

func file_google_protobuf_method_options_proto_rawDescGZIP() []byte {
	file_google_protobuf_method_options_proto_rawDescOnce.Do(func() {
		file_google_protobuf_method_options_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_google_protobuf_method_options_proto_rawDesc), len(file_google_protobuf_method_options_proto_rawDesc)))
	})
	return file_google_protobuf_method_options_proto_rawDescData
}

var file_google_protobuf_method_options_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_google_protobuf_method_options_proto_goTypes = []any{
	(*HttpIntegration)(nil),            // 0: tecmise.protocols.HttpIntegration
	(*descriptorpb.MethodOptions)(nil), // 1: google.protobuf.MethodOptions
}
var file_google_protobuf_method_options_proto_depIdxs = []int32{
	1, // 0: tecmise.protocols.http:extendee -> google.protobuf.MethodOptions
	0, // 1: tecmise.protocols.http:type_name -> tecmise.protocols.HttpIntegration
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_google_protobuf_method_options_proto_init() }
func file_google_protobuf_method_options_proto_init() {
	if File_google_protobuf_method_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_google_protobuf_method_options_proto_rawDesc), len(file_google_protobuf_method_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_google_protobuf_method_options_proto_goTypes,
		DependencyIndexes: file_google_protobuf_method_options_proto_depIdxs,
		MessageInfos:      file_google_protobuf_method_options_proto_msgTypes,
		ExtensionInfos:    file_google_protobuf_method_options_proto_extTypes,
	}.Build()
	File_google_protobuf_method_options_proto = out.File
	file_google_protobuf_method_options_proto_goTypes = nil
	file_google_protobuf_method_options_proto_depIdxs = nil
}
